export const REQUEST = 'REQUEST_'
export const OPEN = 'OPEN_'
export const TOGGLE = 'TOGGLE_'
export const FETCH = 'FETCH_'
export const CLOSE = 'CLOSE_'
export const SET = 'SET_'
export const CLEAN = 'CLEAN_'

export const POSTMAN_API = 'POSTMAN_API'

export const THEME = 'THEME'
export const OPEN_ROUTE = 'OPEN_ROUTE'
export const POST = 'POST'
export const POPUP = 'POPUP'
export const POSTS = 'POSTS'
export const ERROR = 'ERROR'
export const MENU = 'MENU'

export const START = '_START'
export const SUCCESS = '_SUCCESS'
export const FAIL = '_FAIL'